name: Java CI - FinalJayjay

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Running-Automation-Tests:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout code
        uses: actions/checkout@v4

      - name: â˜• Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: ğŸ–¥ï¸ Setup Chrome
        uses: browser-actions/setup-chrome@v1.7.3

      - name: âœ… Grant execute permission for Gradle
        run: chmod +x gradlew

      # Jalankan Web Tests
      - name: ğŸš€ Run Web Tests
        run: ./gradlew runWebTests -Dcucumber.filter.tags="@web"

      # Jalankan API Tests
      - name: ğŸš€ Run API Tests
        run: ./gradlew runApiTests -Dcucumber.filter.tags="@api"

      # Upload Web Test Report
      - name: ğŸ“¤ Upload Web Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: web-report
          path: |
            reports/web_report.html
            reports/web_report.json

      # Upload API Test Report
      - name: ğŸ“¤ Upload API Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-report
          path: |
            reports/api_report.html
            reports/api_report.json

      # Upload Cucumber Report
      - name: ğŸ“¤ Upload Cucumber Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cucumber-report
          path: |
            reports/cucumber.html
            reports/cucumber.json
